spring:
  application:
    name: USERSERVICEDEFAULT

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka
