spring:
  application:
    name: USERSERVICEDEFAULT
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: pradeep@123

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka
